### PR TITLE
Enriched style

### PR DESCRIPTION
**Pull request by ghost**
This isn't ready yet but I thought I'd open the PR in case you wanted to discuss ideas.

The basic `Category` definition is implemented with setoid morphisms but it needs notation and some other stuff. Instances for the structures would also be nice.

### CODE REVIEW

**Comment by ghost** [comment]
It should be possible to reduce some of the noise from all the levels by using anonymous modules. I tried this yesterday and it worked for most of the setoid parts but I ran into some issues later on. I think I may have been a bit too aggressive with the refactoring though.

**Comment by jonsterling** [comment]
OK, cool; this looks good so far! Yes, in the past I have also used anonymous for this purpose, and occasionally I ended up having strange issues. Probably something that can be done incrementally...

**Comment by ghost** [comment]
So I started thinking about multisetoids again after trying to do some stuff related to products and remembering how awful it is. I'm not sure it will scale for something like this yet but I've created a small demonstration for the multisetoid approach at [freebroccolo/agda-operads](https://github.com/freebroccolo/agda-operads).

**Comment by jonsterling** [comment]
Heh... Well, the demonstration looks surprisingly painless! I wonder, did we ever get the generalized version worked out? (Probably doesn't matter for this development though.)

**Comment by ghost** [comment]
@jonsterling I think the generalized version we had was "correct" it's just that there was an issue with using container-like things for the polynomial monad. I think for most interesting cases we would have had to develop standard setoid theory in addition to the multi-setoid theory to deal with higher-order representations.

At one point I did define the multicategory for the free monad on a container [here](https://github.com/freebroccolo/container-calculus/blob/master/Multicats.agda#L96-L137) but I didn't implement any instances. The stuff I've been working on with the logical framework thing is related though I think.

**Comment by ghost** [comment]
Actually the main issue might have been that we couldn't prove the monad laws in most cases (without regular setoids first).

But I think you're right, for this and most other things using lists is probably enough and should already be a big improvement if it scales. We could also use trees (in higher dimensions even) without much additional difficulty but I'm not sure it would be worth it here unless you have some ideas.

**Comment by ghost** [comment]
Going to close this since I've put the current development up at [freebroccolo/agda-groupoids](https://github.com/freebroccolo/agda-groupoids).

**Pull request closed without merging**
